export const FETCH_FLIGHTS = "FETCH_FLIGHTS";
export const FETCH_FLIGHTS_COMPLETED = "FETCH_FLIGHTS_COMPLETED";
export const FETCH_FLIGHTS_ERROR = "FETCH_FLIGHTS_ERROR";

export const CREATE_FLIGHT = "CREATE_FLIGHT";
export const CREATE_FLIGHT_COMPLETED = "CREATE_FLIGHT_COMPLETED";
export const CREATE_FLIGHT_ERROR = "CREATE_FLIGHT_ERROR";

export const MANIPULATE_FLIGHTS = "MANIPULATE_FLIGHTS";
export const MANIPULATE_FLIGHTS_COMPLETED = "MANIPULATE_FLIGHTS_COMPLETED";
export const MANIPULATE_FLIGHTS_ERROR = "MANIPULATE_FLIGHTS_ERROR";

export const LOADING_FINISHED = "LOADING_FINISHED";
export const LOADING_STARTED = "LOADING_STARTED";

export const PAGINATION_STARTED = "PAGINATION_STARTED";
export const PAGINATION_COMPLETED = "PAGINATION_COMPLETED";
